### ISSUE TITLE
The aruco box is not 1x1x1 m

### ISSUE THREAD

**Issue by JackMaisi** [FabianReister/gazebo_aruco_box#2]
First, thanks for the model but i think there is some kind of issue with the size of the box. 
The defined geometry is 1x1x1m , however the mesh around the cube is 2x2x2m. So the box appears as 2x2x2m.
I added a box in gazebo with 1x1x1m and also checked the blender file and the box was 2x2x2m.

![comparison_box](https://user-images.githubusercontent.com/35350137/116267765-fdc10200-a77c-11eb-9794-bc2670d4b298.png)

![Screenshot from 2021-04-27 17-11-51](https://user-images.githubusercontent.com/35350137/116267906-18937680-a77d-11eb-9dad-049bf84800f0.png)

![Screenshot from 2021-04-27 17-23-10](https://user-images.githubusercontent.com/35350137/116268081-45e02480-a77d-11eb-9bf4-040fa232fd82.png)

**Comment by FabianReister** [comment]
@JackMaisi thanks for pointing this out. If you have already fixed the box size, feel free to open a pull request.

**Comment by redvinaa** [comment]
Hi, I opened a PR for this, see #3.
